export const RESPONSE_MESSAGES = {
    CATEGORY_CREATED : "Category Created Successfully",
    CATEGORIES_FETCHED: "Categories Fetched Successfully",
    CATEGORY_FETCHED: "Category Fetched Successfully",  
    CATEGORY_NOT_FOUND: "Category Not Found",
    CATEGORY_UPDATED: "Category Updated Successfully",
    CATEGORY_DELETED: "Category Deleted Successfully",
    SUB_CATEGORY_CREATED: "Sub Category Created Successfully",
    SUB_CATEGORIES_FETCHED: "Sub Categories Fetched Successfully",
    SUB_CATEGORY_FETCHED: "Sub Category Fetched Successfully",
    SUB_CATEGORY_NOT_FOUND: "Sub Category Not Found",
    SUB_CATEGORY_UPDATED: "Sub Category Updated Successfully",
    SUB_CATEGORY_DELETED: "Sub Category Deleted Successfully",
    BRANCH_CREATED: "Branch Created Successfully",
    BRANCHES_FETCHED: "Branches Fetched Successfully",
    BRANCH_FETCHED: "Branch Fetched Successfully",
    BRANCH_NOT_FOUND: "Branch Not Found",
    BRANCH_UPDATED: "Branch Updated Successfully",
    BRANCH_DELETED: "Branch Deleted Successfully",
    VENDOR_CREATED: "Vendor Created Successfully",
    VENDORS_FETCHED: "Vendors Fetched Successfully",
    VENDOR_FETCHED: "Vendor Fetched Successfully",
    VENDOR_NOT_FOUND: "Vendor Not Found",
    VENDOR_UPDATED: "Vendor Updated Successfully",
    VENDOR_DELETED: "Vendor Deleted Successfully",
    VENDOR_STATUS_UPDATED: "Vendor Status Updated Successfully",
};
